// Generated by https://quicktype.io

export interface EstadoCivil {
    cod_est: number;
    des_est: string;
}

export interface Generos {
    cod_gen: number;
    des_gen: string;
}

export interface TipoEmpleado {
    estado: string;
    codigo: number;
    nombre: string;
}

export interface Ciudades {
    cod_pai: string;
    cod_dep: string;
    cod_ciu: string;
    nom_dep: string;
}

export interface Departamentos {
    cod_pai: string;
    cod_dep: string;
    nom_dep: string;
}

export interface Paises {
    cod_pai: number;
    nom_pai: string;
}

